# Original idea by @ISnackable. Thanks to him for handling the hardest parts!
# https://github.com/ISnackable/YTCubePlus/blob/main/.github/workflows/Build.yml

name: Build uYouPlusExtra

on:
  workflow_dispatch:
    inputs:
      build_ipa:
        description: "Build package for sideloading"
        default: true
        type: boolean
      build_debs:
        description: "Build packages for jailbroken devices"
        default: false
        type: boolean
      sdk_version:
        description: "iOS SDK version to be used during build"
        default: "17.0.3"
        type: string
      xcode_version:
        description: "Xcode version to be used during build"
        default: "13.4.1"
        type: string
      uyouplus_version:
        description: "The version of uYouPlusExtra"
        type: string
        required: true
      youtube_version:
        description: "The version of YouTube (or 'latest' to use the latest)"
        default: "latest"
        type: string
      uyou_version:
        description: "The version of uYou (or 'latest' to use the latest)"
        default: "latest"
        type: string
      decrypted_youtube_url:
        description: "The direct URL to the decrypted YouTube ipa (or 'latest' to use the latest)"
        default: "latest"
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        type: boolean
      bundle_id:
        description: "Modify the bundle ID. Not recommended"
        default: "com.google.ios.youtube"
        type: string
      app_name:
        description: "Modify the name of the app on the Home Screen. Not recommended"
        default: "YouTube"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build uYouPlusExtra
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      # Symlinked .gitconfig causes issues
      - name: Check for symlinked global .gitconfig
        if: ${{ env.ACT }}
        run: '! readlink $HOME/.gitconfig'

      - name: Change Xcode version
        if: ${{ !env.ACT }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ inputs.xcode_version }}

      - name: Check Xcode version
        run: xcodebuild -version | grep "Xcode ${{ inputs.xcode_version }}"

      - name: Check for Homebrew
        if: ${{ env.ACT }}
        run: command -v brew

      - name: Install Dependencies
        run: brew install curl dpkg jq ldid make node svn wget xz

      - name: Set environment variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 
          echo "YOUTUBE_VERSION=${{ inputs.youtube_version }}" >> $GITHUB_ENV
          echo "UYOU_VERSION=${{ inputs.uyou_version }}" >> $GITHUB_ENV
          echo "UYOUPLUS_VERSION=${{ inputs.uyouplus_version }}" >> $GITHUB_ENV
          echo "YOUTUBE_URL=${{ inputs.decrypted_youtube_url }}" >> $GITHUB_ENV

      - name: Resolve YouTube version
        if: ${{ inputs.youtube_version == 'latest' }}
        run: |
          echo "YOUTUBE_VERSION=$(curl -X POST -d '{"country":"us","app":"YouTube"}' https://armconverter.com/api/appinfo | jq .results[0].version | tr -d '"')" >> $GITHUB_ENV
      
      - name: Resolve uYou version
        if: ${{ inputs.uyou_version == 'latest' }}
        run: |
          echo "UYOU_VERSION=$(curl https://miro92.com/repo/Packages.bz2 | bzip2 -d | grep -A1 -e '^Package: com.miro.uyou$' | tail -1 | cut -c 10-)" >> $GITHUB_ENV

      - name: Resolve YouTube URL
        if: ${{ inputs.decrypted_youtube_url == 'latest' }}
        run: |
          TOKEN=$(curl -X POST -H "Referer: https://armconverter.com/decryptedappstore/us/YouTube" -H "Cookie: session=$DECRYPTEDAPPSTORE_SESSION_TOKEN" "https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/$YOUTUBE_VERSION/prepare" | jq .token | tr -d '"')
          if [[ $TOKEN == 'null' || -z $TOKEN ]]; then exit 1; fi
          echo "YOUTUBE_URL=https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/$YOUTUBE_VERSION?token=$TOKEN" >> $GITHUB_ENV
        env:
          DECRYPTEDAPPSTORE_SESSION_TOKEN: ${{ secrets.DECRYPTEDAPPSTORE_SESSION_TOKEN }}

      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref || github.event.repository.default_branch }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          path: main
          submodules: recursive
      
      - name: IPA Caching
        if: ${{ inputs.build_ipa }}
        id: IPA
        uses: actions/cache@v3
        env:
          cache-name: YouTube-${{ env.YOUTUBE_VERSION }}-IPA
        with:
          path: main/YouTube.ipa
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download YouTube IPA
        if: ${{ steps.IPA.outputs.cache-hit != 'true' && inputs.build_ipa }}
        run: |
          wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa && echo -e "==> \033[1mYouTube v${{ env.YOUTUBE_VERSION }} downloaded! \033[0m"
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Setup Theos Jailed
        if: ${{ inputs.build_ipa }}
        uses: actions/checkout@v3
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        if: ${{ inputs.build_ipa }}
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: SDK Caching
        id: SDK
        uses: actions/cache@v3
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}
      
      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          svn checkout -q https://github.com/arichorn/sdks/trunk/iPhoneOS${{ inputs.sdk_version }}.sdk
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build .ipa
        if: ${{ inputs.build_ipa }}
        run: |
          cd ${{ github.workspace }}/main
          make package
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"
        env:
          THEOS: ${{ github.workspace }}/theos
          BUNDLE_ID: ${{ inputs.bundle_id }}
          DISPLAY_NAME: ${{ inputs.app_name }}
          FINALPACKAGE: ${{ inputs.create_release }}
          IPA: YouTube.ipa

      - name: Build .debs
        if: ${{ inputs.build_debs }}
        run: |
          cd ${{ github.workspace }}/main
          make package
          make clean package THEOS_PACKAGE_SCHEME=rootless
        env:
          THEOS: ${{ github.workspace }}/theos
          JAILBROKEN: 1
          FINALPACKAGE: ${{ inputs.create_release }}

      - name: Upload Artifacts
        if: ${{ inputs.build_ipa || inputs.build_debs }}
        uses: actions/upload-artifact@v3
        with:
          name: uYouPlusExtra_${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-${{ env.UYOUPLUS_VERSION }}
          path: ${{ github.workspace }}/main/packages/*
          if-no-files-found: error

      - name: Create Release
        if: ${{ !env.ACT && inputs.create_release }}
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-${{ env.UYOUPLUS_VERSION }}-(${{ github.run_number }})
          name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-${{ env.UYOUPLUS_VERSION }}-(${{ github.run_number }})
          files: main/packages/*
          draft: true
